### ISSUE TITLE
Link to YouTube video

### ISSUE THREAD

**Issue by berndporr** [Alexandros-Charitonidis/X-Wing-IIR-Filltering#5]
The GU Wiki seems to have no link to your video. Would be good if you could add it to git here.

**Comment by atadema** [comment]
There was a slight error made when uploading the video on my own private webserver, which apparently did not work in Moodle and also Github apparently does not allow direct embedding of video!. 
But we found a solution! Inserting a clickable image of a video thumbnail offers a almost as good experience! The video is now uploaded it to YouTube, apologies for any inconvenience this might have caused! 
https://www.youtube.com/watch?v=-S1iXpoRs1U
